version: "3.7"
services:
  db_:
    image: postgres:11
    container_name: db_
    #volumes:
    #  - ./data:/var/lib/postgresql/data
    env_file:
      - .env-docker

  app:
    build:
      context: .
    env_file:
      - .env-docker
    container_name: utils_app
    command: ["/app/docker/app.sh"]
    ports:
      - 9998:8000
    depends_on:
      - db_
      - celery
      - redis

  celery:
    build:
      context: .
    env_file:
      - .env-docker
    container_name: celery_app
    command: ["/app/docker/celery.sh"]
    depends_on:
      - redis

  redis:
    image: redis:5
    container_name: redis_app
