"""empty message

Revision ID: 1863d186589c
Revises: 
Create Date: 2025-06-08 19:10:22.550230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1863d186589c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usd', sa.Float(), nullable=False),
    sa.Column('eur', sa.Float(), nullable=False),
    sa.Column('eur_usd', sa.Float(), nullable=False),
    sa.Column('bitcoin', sa.Float(), nullable=False),
    sa.Column('usd_buy_tb', sa.Float(), nullable=False),
    sa.Column('usd_sell_tb', sa.Float(), nullable=False),
    sa.Column('eur_buy_tb', sa.Float(), nullable=False),
    sa.Column('eur_sell_tb', sa.Float(), nullable=False),
    sa.Column('update_cb', sa.DateTime(timezone=True), nullable=False),
    sa.Column('update_tb_and_bitcoin', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rates_id'), 'rates', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rates_id'), table_name='rates')
    op.drop_table('rates')
    # ### end Alembic commands ###
